apiVersion: v2
name: simple-db-app-chart-with-dependency
description: A Helm chart for simple db app with mariadb as dependency
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: mariadb
    version: 10.1.1
    repository: https://charts.bitnami.com/bitnami
