images:
  app:
    repository: htmlprogrammer2001/simple-db-app
    tag: "1.0"
    pullPolicy: IfNotPresent

  migration:
    repository: simple-db-app-migration
    tag: "1.0"
    pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: NodePort
  port: 3000
  nodePort: 32001

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

mariadb:
  auth:
    rootPassword: root
