images:
  app:
    repository: htmlprogrammer2001/simple-db-app
    tag: "1.0"
    pullPolicy: IfNotPresent

  migration:
    repository: htmlprogrammer2001/simple-db-app-migration
    tag: "1.0"
    pullPolicy: IfNotPresent

replicaCount: 1

env:
  - name: DB_HOST
    value: "maria-db-mariadb"

  - name: DB_PORT
    value: "3306"

  - name: DB_USER
    value: "root"

  - name: DB_PASSWORD
    value: "root"

  - name: DB_NAME
    value: "app"

service:
  type: NodePort
  port: 3000
  nodePort: 32001

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
